# Generated by Django 6.0.6 on 2026-06-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_type', models.CharField(blank=True, default='', max_length=100)),
                ('trip_purpose', models.CharField(blank=True, default='leisure', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='itinerary.itinerary')),
            ],
            options={
                'db_table': 'packing_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('toiletries', 'Toiletries & Personal Care'), ('electronics', 'Electronics & Gadgets'), ('documents', 'Documents & Money'), ('health', 'Health & Medical'), ('misc', 'Miscellaneous')], default='misc', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_packed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('high', 'Essential'), ('medium', 'Normal'), ('low', 'Optional')], default='medium', max_length=10)),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing.packinglist')),
            ],
            options={
                'db_table': 'packing_items',
                'ordering': ['category', 'name'],
            },
        ),
    ]
