# Generated by Django 6.0.6 on 2026-06-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetestimate',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_estimates', to='itinerary.itinerary'),
        ),
    ]
