# Generated by Django 6.0.6 on 2026-06-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourismInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255, unique=True)),
                ('local_customs', models.TextField(blank=True, default='')),
                ('language_tips', models.TextField(blank=True, default='')),
                ('currency_info', models.TextField(blank=True, default='')),
                ('best_time_to_visit', models.CharField(blank=True, default='', max_length=150)),
                ('safety_rating', models.CharField(blank=True, default='', max_length=50)),
                ('visa_requirements', models.TextField(blank=True, default='')),
                ('ai_generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tourism Info',
                'db_table': 'tourism_info',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('entry_fee', models.CharField(blank=True, default='Free', max_length=100)),
                ('opening_hours', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tourism_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='tourism.tourisminfo')),
            ],
            options={
                'db_table': 'attractions',
                'ordering': ['name'],
            },
        ),
    ]
