from django.db import models
from django.conf import settings

class BudgetEstimate(models.Model):
    """Estimated trip budget generated by AI or user, associated with an itinerary."""
    
    itinerary = models.ForeignKey(
        'itinerary.Itinerary',
        on_delete=models.CASCADE,
        related_name='budget_estimates',
        null=True, blank=True
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='budget_estimates'
    )
    total_estimated = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    
    # Breakdown containing categories and their estimated costs
    # Example: {"flights": 800, "hotels": 600, "food": 300, "activities": 200, "transport": 150, "misc": 100}
    breakdown = models.JSONField(default=dict, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'budget_estimates'
        ordering = ['-created_at']

    def __str__(self):
        dest = self.itinerary.destination if self.itinerary else "General"
        return f"Budget Estimate for {dest}: {self.total_estimated} {self.currency}"


class Expense(models.Model):
    """Actual logged expense during the trip."""
    
    CATEGORY_CHOICES = [
        ('flights', 'Flights/Transport to Destination'),
        ('accommodation', 'Accommodation'),
        ('food', 'Food & Dining'),
        ('activities', 'Activities & Sightseeing'),
        ('local_transport', 'Local Transportation'),
        ('shopping', 'Shopping'),
        ('medical', 'Medical/Insurance'),
        ('misc', 'Miscellaneous'),
    ]

    itinerary = models.ForeignKey(
        'itinerary.Itinerary',
        on_delete=models.CASCADE,
        related_name='expenses'
    )
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default='misc')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    description = models.CharField(max_length=255, blank=True, default='')
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'expenses'
        ordering = ['-date', '-created_at']

    def __str__(self):
        return f"{self.category.title()} - {self.amount} {self.currency} ({self.date})"
