# Generated by Django 6.0.6 on 2026-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255, unique=True)),
                ('required_vaccinations', models.JSONField(blank=True, default=list)),
                ('recommended_vaccinations', models.JSONField(blank=True, default=list)),
                ('health_risks', models.TextField(blank=True, default='')),
                ('insurance_recommendations', models.TextField(blank=True, default='')),
                ('advisory_notes', models.TextField(blank=True, default='', help_text='AI-generated advisory notes')),
                ('ai_generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medical Info',
                'db_table': 'medical_info',
            },
        ),
        migrations.CreateModel(
            name='UserMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of allergies')),
                ('medications', models.JSONField(blank=True, default=list, help_text='Current medications')),
                ('blood_type', models.CharField(blank=True, default='', max_length=5)),
                ('medical_conditions', models.TextField(blank=True, default='')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'user_medical_profiles',
            },
        ),
    ]
