# Generated by Django 6.0.6 on 2026-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_star_rating', models.PositiveIntegerField(default=3)),
                ('min_budget', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('must_have_amenities', models.JSONField(blank=True, default=list, help_text='e.g. ["wifi", "pool", "gym", "breakfast"]')),
                ('preferred_location_type', models.CharField(blank=True, default='central', help_text='e.g. central, beachfront, quiet suburb', max_length=50)),
            ],
            options={
                'db_table': 'hotel_preferences',
            },
        ),
        migrations.CreateModel(
            name='HotelRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('star_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('booking_url', models.URLField(blank=True, default='')),
                ('ai_notes', models.TextField(blank=True, default='', help_text='AI-generated recommendation notes')),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotel_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
