# Generated by Django 6.0.6 on 2026-06-06 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('itinerary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelrecommendation',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_recommendations', to='itinerary.itinerary'),
        ),
        migrations.AddField(
            model_name='hotelrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_recommendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
