# Generated by Django 6.0.6 on 2026-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255, unique=True)),
                ('emergency_numbers', models.JSONField(blank=True, default=dict, help_text='e.g. {"police": "112", "ambulance": "112", "fire": "112"}')),
                ('embassy_info', models.TextField(blank=True, default='')),
                ('safety_tips', models.TextField(blank=True, default='')),
                ('travel_warnings', models.TextField(blank=True, default='')),
                ('ai_generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Emergency Info',
                'db_table': 'emergency_info',
            },
        ),
    ]
